export interface TurbineLog {
    log_time: string,
    name: string,
    site_id: number,
    turbine_log_id: number,
    turbine_id: number,
    account_id: number,
    value: string,
    alarm_class: string,
    turbine_name: string,
    isDeactive: string,
    power: string,
    power_value: string,
    wind: string,
    gen: string,
    rotor: string,
    temp_a: string,
    react: string,
    temp_n: string,
    wind_value: string,
    nacelle: string,
}